# Generated by Django 5.0.4 on 2024-05-09 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_alter_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='employee_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
