# Generated by Django 5.0.4 on 2024-05-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_invoice_employee_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='unit',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
